import type { Consultation } from "../types/consultation.types";
import { getUsageMock } from "../config/doctorInfo";
import { loadDoctorProfile } from "../service/doctorProfileService";
import { t, getLang } from "../config/i18n";
import { useLanguage } from "../hooks/useLanguage";

interface PrescriptionDocumentProps {
  consultation: Consultation;
}

export const PrescriptionDocument = ({ consultation }: PrescriptionDocumentProps) => {
  // força re-render quando idioma muda
  useLanguage();

  const doctor = loadDoctorProfile();
  const lang = getLang();

  // Data formatada conforme idioma
  const today: string = new Date().toLocaleDateString(lang === "pt" ? "pt-BR" : "en-US");

  return (
    <div className="pdf-wrapper">
      <div id="pdf-document">
        {/* Header */}
        <header className="pdf-header">
          <img src="/logo-mc.png" className="pdf-logo" />

          <div className="pdf-header-right">
            <div className="pdf-doctor-name">{doctor.name}</div>
            <div className="pdf-doctor-specialty">{doctor.specialty}</div>
            <div className="pdf-doctor-meta">
              CRM {doctor.crm} — {doctor.clinicPhone}
            </div>
          </div>
        </header>

        {/* Título */}
        <h2 className="pdf-title">
          {lang === "pt" ? "PRESCRIÇÃO MÉDICA" : "MEDICAL PREVIEW"}
        </h2>

        {/* Paciente + Data */}
        <div className="pdf-row">
          <span className="pdf-label">{lang === "pt" ? "Paciente:" : "Patient:"}</span>
          <span className="pdf-value">{consultation.patientName}</span>

          <span className="pdf-label" style={{ marginLeft: "auto" }}>
            {lang === "pt" ? "Data:" : "Date:"}
          </span>
          <span className="pdf-value">{today}</span>
        </div>

        {/* Medicação */}
        <section className="pdf-section">
          <div className="pdf-section-title">
            {lang === "pt" ? "Medicação Prescrita" : "Prescribed Medication"}
          </div>

          {consultation.diagnosis.medicamentosComuns.map((med: string, index: number) => (
            <div className="pdf-med-item" key={index}>
              <div className="pdf-med-index">{String(index + 1).padStart(2, "0")}.</div>

              <div className="pdf-med-name">{med}</div>

              {/* Uso padrão (mock) */}
              <div className="pdf-med-usage">{getUsageMock(med)}</div>
            </div>
          ))}
        </section>

        {/* Observações */}
        <section className="pdf-section">
          <div className="pdf-section-title">{t("observations")}</div>

          <p className="pdf-observations-text">
            {lang === "pt"
              ? "Uso educacional, não substitui decisão médica. Esta prescrição é um exemplo gerado automaticamente pelo sistema MedNote.IA – Médico Copilot."
              : "Educational use only, does not replace medical judgment. This prescription is an example automatically generated by the MedNote.IA – Medical Copilot system."}
          </p>
        </section>

        {/* Rodapé */}
        <footer className="pdf-footer">
          <div className="pdf-footer-line" />
          <div className="pdf-footer-name">{doctor.name}</div>
          <div className="pdf-footer-crm">CRM {doctor.crm}</div>
        </footer>
      </div>
    </div>
  );
};
